<?xml version="1.0"?>
<robot name="mecanum_amr" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- ==================== Properties ==================== -->
  <xacro:property name="base_width"  value="0.60"/>
  <xacro:property name="base_length" value="0.80"/>
  <xacro:property name="base_height" value="0.20"/>
  <xacro:property name="base_mass"   value="50.0"/>

  <xacro:property name="wheel_radius" value="0.075"/>
  <xacro:property name="wheel_width"  value="0.05"/>
  <xacro:property name="wheel_mass"   value="2.0"/>

  <xacro:property name="wheel_x_offset" value="0.25"/>
  <xacro:property name="wheel_y_offset" value="0.35"/>
  <xacro:property name="wheel_z_offset" value="-0.05"/>

  <!-- ==================== Macros ==================== -->
  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${m*(h*h+d*d)/12}" ixy="0" ixz="0"
               iyy="${m*(w*w+d*d)/12}" iyz="0"
               izz="${m*(w*w+h*h)/12}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0"
               iyy="${m*(3*r*r+h*h)/12}" iyz="0"
               izz="${m*r*r/2}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="mecanum_wheel" params="name x y z roll">
    <link name="${name}_link">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="dark_gray">
          <color rgba="0.2 0.2 0.2 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
    </link>

    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child  link="${name}_link"/>
      <origin xyz="${x} ${y} ${z}" rpy="${roll} 0 0"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.1" friction="0.1"/>
    </joint>
  </xacro:macro>

  <!-- ==================== Base Link ==================== -->
  <link name="base_footprint"/>

  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child  link="base_link"/>
    <origin xyz="0 0 ${wheel_radius - wheel_z_offset}" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0.1 0.4 0.8 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="${base_mass}" w="${base_width}" h="${base_height}" d="${base_length}"/>
  </link>

  <!-- ==================== Wheels ==================== -->
  <xacro:mecanum_wheel name="front_left_wheel"  x=" ${wheel_x_offset}" y=" ${wheel_y_offset}" z="${wheel_z_offset}" roll="${pi/2}"/>
  <xacro:mecanum_wheel name="front_right_wheel" x=" ${wheel_x_offset}" y="-${wheel_y_offset}" z="${wheel_z_offset}" roll="${pi/2}"/>
  <xacro:mecanum_wheel name="rear_left_wheel"   x="-${wheel_x_offset}" y=" ${wheel_y_offset}" z="${wheel_z_offset}" roll="${pi/2}"/>
  <xacro:mecanum_wheel name="rear_right_wheel"  x="-${wheel_x_offset}" y="-${wheel_y_offset}" z="${wheel_z_offset}" roll="${pi/2}"/>

  <!-- ==================== LiDAR ==================== -->
  <link name="lidar_link">
    <visual>
      <geometry>
        <cylinder radius="0.05" length="0.07"/>
      </geometry>
      <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.05" length="0.07"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia m="0.5" r="0.05" h="0.07"/>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="lidar_link"/>
    <origin xyz="0.3 0 ${base_height/2 + 0.035}" rpy="0 0 0"/>
  </joint>

  <!-- LiDAR Gazebo plugin -->
  <gazebo reference="lidar_link">
    <sensor name="lidar" type="ray">
      <always_on>true</always_on>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1.0</resolution>
            <min_angle>-3.14159</min_angle>
            <max_angle>3.14159</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.12</min>
          <max>20.0</max>
          <resolution>0.015</resolution>
        </range>
      </ray>
      <plugin name="scan" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <namespace>/</namespace>
          <remapping>~/out:=scan</remapping>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>lidar_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>

  <!-- ==================== Camera (QR okuma için) ==================== -->
  <link name="camera_link">
    <visual>
      <geometry>
        <box size="0.04 0.10 0.04"/>
      </geometry>
      <material name="dark_gray">
        <color rgba="0.2 0.2 0.2 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.04 0.10 0.04"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="0.1" w="0.10" h="0.04" d="0.04"/>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="camera_link"/>
    <origin xyz="0.35 0 ${base_height/2}" rpy="0 0 0"/>
  </joint>

  <link name="camera_optical_link"/>
  <joint name="camera_optical_joint" type="fixed">
    <parent link="camera_link"/>
    <child  link="camera_optical_link"/>
    <origin xyz="0 0 0" rpy="-${pi/2} 0 -${pi/2}"/>
  </joint>

  <gazebo reference="camera_link">
    <sensor name="camera" type="camera">
      <always_on>true</always_on>
      <visualize>true</visualize>
      <update_rate>30</update_rate>
      <camera>
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <frame_name>camera_optical_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>

  <!-- ==================== Lift Mechanism ==================== -->
  <link name="lift_platform_link">
    <visual>
      <geometry>
        <box size="0.50 0.40 0.02"/>
      </geometry>
      <material name="orange">
        <color rgba="0.9 0.5 0.1 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.50 0.40 0.02"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="5.0" w="0.40" h="0.02" d="0.50"/>
  </link>

  <joint name="lift_joint" type="prismatic">
    <parent link="base_link"/>
    <child  link="lift_platform_link"/>
    <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="0.0" upper="0.30" effort="500" velocity="0.1"/>
    <dynamics damping="10.0" friction="5.0"/>
  </joint>

  <!-- ==================== Gazebo Base Settings ==================== -->
  <gazebo reference="base_link">
    <material>Gazebo/Blue</material>
    <mu1>0.8</mu1>
    <mu2>0.8</mu2>
  </gazebo>

  <!-- Differential drive plugin (mecanum yaklaşımı için) -->
  <gazebo>
    <plugin name="mecanum_drive_controller" filename="libgazebo_ros_planar_move.so">
      <ros>
        <remapping>cmd_vel:=cmd_vel</remapping>
      </ros>
      <update_rate>100</update_rate>
      <publish_rate>10</publish_rate>
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_footprint</robot_base_frame>
    </plugin>
  </gazebo>

</robot>

